# Generated by Django 5.1.1 on 2024-10-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='tradeid',
            field=models.UUIDField(null=True),
        ),
    ]
